### ISSUE TITLE
[#6] Cosmetic additions to Discord embed and widened scope of handled JIRA events

### ISSUE THREAD

**Issue by ChipWolf** [3esi/jira-discord-lambda#7]
**As a** `jira-discord-lambda` user 
**I want to** see more info in Discord from JIRA
**So that I** can increase engagement and see more context with events from JIRA

**Background**
Currently, `jira-discord-lambda` is an MVP which handles a limited scope of events from JIRA and provides the bare minimum of the context available in the event.
In addition to a few simple cosmetic fixes such as making use of more of the available Discord embed objects, my team would like to see some changes made.

**Acceptance Criteria**
- Handle all issue types and move filtering of issue type to JQL in the JIRA webhook config
- Show the current issue type and icon in the embed's footer
- Show the initiator's avatar in the embed's thumbnail
- Show the current issue status in the embed
- Handle status change events as part of `issue_updated` and display them as an additional field
- Allow configuration of the above _(longer term goal)_

**Comment by andyczerwonka** [comment]
Ideally we split this into a couple of concerns.

1. Cosmetic embed
2. Widen scope to all issue types

**Comment by ChipWolf** [comment]
Sounds good, probably worth packing the `issue_updated` changes into point 2 @andyczerwonka

**Comment by andyczerwonka** [comment]
Replacing this issue with #8 and #9.
